### ISSUE TITLE
feature: Change default branch to main

### ISSUE THREAD

**Issue by thiiagoms** [ekkopy/wifi-list#1]
Change default branch to main

**Comment by kaushikaryan04** [comment]
Hey can you assign it to me? And invite me as a contributor

**Comment by thiiagoms** [comment]
> 
> 
> Hey can you assign it to me? And invite me as a contributor

**Comment by thiiagoms** [comment]
> 
> 
> Hey can you assign it to me? And invite me as a contributor

Did you fork this repository ? I'm so sorry, that was my mistake, sorry about that.
